```{r setup, include=FALSE} 
knitr::opts_chunk$set(echo = TRUE,tidy.opts=list(width.cutoff=80), tidy=FALSE) 
```

```{r package, message=FALSE}
library(lubridate)
library(ggplot2)
library(forecast)  
library(Kendall)
library(tseries)
library(outliers)
library(tidyverse)

#install.packages("smooth")
library(smooth)
```

```{r}
#importing datasets

raw_load <- read.csv(file="Data_TOPOST/converting files to csv/load.csv", header = TRUE, dec = ".", sep=",") #na.strings = c("","NA")) 
raw_temp <- read.csv(file="Data_TOPOST/converting files to csv/temperature.csv", header = TRUE, dec = ".", sep=",")
raw_humidity <- read.csv(file="Data_TOPOST/converting files to csv/relative_humidity.csv", header = TRUE, dec = ".", sep=",")

#cleaning load dataset
raw_load <- raw_load[,-1]

#cleaning more and calculating daily averages
raw_load_2<- raw_load %>%
  drop_na() %>%
  mutate(date = mdy(date)) %>%
  mutate_at(2:25, ~ as.numeric(.))

load <- raw_load_2 %>%
  mutate(daily_load = rowMeans(raw_load_2[,2:25], na.rm=TRUE))

load <- load[,c(1,26)]

#cleaning and calculating daily temp averages
raw_temp_2 <- raw_temp %>%
  drop_na() %>%
  mutate(date = dmy(date)) %>%
  mutate_at(3:30, ~ as.numeric(.))

temp <- raw_temp_2%>%
  mutate(hourly_avg = rowMeans(raw_temp_2[,3:30], na.rm=TRUE))%>%
  group_by(date) %>%
  summarise(daily_temp=mean(hourly_avg))

#cleaning and calculating daily humidity
raw_humidity_2 <- raw_humidity %>%
  drop_na() %>%
  mutate(date = dmy(date)) %>%
  mutate_at(3:30, ~ as.numeric(.))

humidity <- raw_humidity_2%>%
  mutate(hourly_avg = rowMeans(raw_humidity_2[,3:30], na.rm=TRUE))%>%
  group_by(date) %>%
  summarise(daily_humidity=mean(hourly_avg))

```

```{r june}
# Create a time series object using msts()
ts_load1 <- msts(load$daily_load, seasonal.periods = c(24), start = c(2010, 6, 1), end = c(2010, 6, 30))

auto.arima(ts_load1)

arima_load1<-Arima(ts_load1,order=c(0,1,2),seasonal=c(2,0,1),include.mean=TRUE, include.drift = TRUE)

# Generate forecasts for the specified period
forecast_result_load1 <- forecast(arima_load1, h = 30)  #forecast 30 days into the future

# Print the forecasted values
print(forecast_result_load1)
```

```{r july}
# Create a time series object using msts()
ts_load2 <- msts(load$daily_load, seasonal.periods = c(24), start = c(2010, 7, 1), end = c(2010, 7, 30))

auto.arima(ts_load2)

arima_load2<-Arima(ts_load2,order=c(0,1,2),seasonal=c(2,0,1),include.mean=TRUE, include.drift = TRUE)

# Generate forecasts for the specified period
forecast_result_load2 <- forecast(arima_load2, h = 30)  #forecast 30 days into the future

# Print the forecasted values
print(forecast_result_load2)

```

```{r}

```

